#
# .zshrc {{{
# Executes commands at the start of an interactive session.
#

if [[ -n $ZSH_DEBUG ]]; then; echo 'Loading $HOME/.zshrc'; fi

# }}}
###################################################################################################

# Terminal settings
# -ixon: disable START/STOP output
# stop|start undef: disable scren lock for Ctl-S. needs even use -ixon
# speed extb: workstation io speed. extb is 38400(max)
#
# defaults:
#  speed 9600 baud; rows 92; columns 425;
#  intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; start = ^Q; stop = ^S; susp = ^Z; dsusp = ^Y; rprnt = ^R; werase = ^W; lnext = ^V; discard = ^O; status = ^T; min = 1; time = 0;
#  -parenb -parodd cs8 hupcl -cstopb cread -clocal -crtscts
#  -ignbrk brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff ixany imaxbel iutf8
#  opost -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
#  isig icanon iexten echo echoe -echok -echonl -noflsh -tostop -echoprt echoctl echoke -flusho -extproc

stty -iutf8 -ixon stop undef start undef speed extb > /dev/null 2>&1

# }}}
###################################################################################################

# Zsh configs {{{

# Load the zsh modules (module list available on man zshmodules)
zmodload 'zsh/attr' 'zsh/stat' 'zsh/pcre' 'zsh/net/socket' 'zsh/db/gdbm'
# Initialize the commnad completions
autoload -Uz compdef compinit; compinit


REPORTTIME=3               # Output zsh command response
unsetopt CORRECT           # Disable zsh correct
setopt IGNOREEOF           # Disable '^D' logout keybind
setopt MAGIC_EQUAL_SUBST   # Enable show prefix = in completions
setopt MARK_DIRS           # Auto completion on folder end slash
setopt LIST_TYPES          # Marking file info on completion list
setopt ALWAYS_LAST_PROMPT  # Keep cursor on completion
setopt GLOBDOTS            # Show dotfiles on completion

# directory
setopt AUTO_CD              # Auto changes to a directory without typing cd.
setopt AUTO_PUSHD           # Push the old directory onto the stack on cd.
setopt PUSHD_IGNORE_DUPS    # Do not store duplicates in the stack.
setopt PUSHD_SILENT         # Do not print the directory stack after pushd or popd.
setopt PUSHD_TO_HOME        # Push to home directory when no argument is given.
setopt CDABLE_VARS          # Change directory to a path stored in a variable.
setopt AUTO_NAME_DIRS       # Auto add variable-stored paths to ~ list.
setopt MULTIOS              # Write to multiple descriptors.
setopt EXTENDED_GLOB        # Use extended globbing syntax.
unsetopt CLOBBER            # Do not overwrite existing files with > and >>.
                            # Use >! and >>! to bypass.

# }}}
###################################################################################################

# Load local modules

for f in $(print -l ${HOME}/.zsh/*.zsh $ZSH_MODULE/*.zsh $ZSH_PLUGIN/zsh-users/{zsh-completions,zsh-syntax-highlighting}/*.plugin.zsh);
  do source $f
done

# }}}
###################################################################################################
#
# Zsh history {{{
#

HISTFILE="${HOME}/.zsh_history"
HISTSIZE=5000000000000           # Memory History size
SAVEHIST=10000000000000          # Save History size
setopt BANG_HIST                 # Treat the '!' character specially during expansion
setopt EXTENDED_HISTORY          # Write the history file in the ':start:elapsed;command' format
setopt HIST_EXPAND               # Expand automatically history to completion
setopt HIST_EXPIRE_DUPS_FIRST    # Expire a duplicate event first when trimming history
setopt HIST_FIND_NO_DUPS         # Do not display a previously found event
setopt HIST_IGNORE_ALL_DUPS      # Delete an old recorded event if a new event is a duplicate
setopt HIST_IGNORE_DUPS          # Do not record an event that was just recorded again
setopt HIST_IGNORE_SPACE         # Do not record an event starting with a space
setopt HIST_SAVE_NO_DUPS         # Do not write a duplicate event to the history file
setopt HIST_VERIFY               # Do not execute immediately upon history expansion
setopt INC_APPEND_HISTORY        # Write to the history file immediately, not when the shell exits
setopt SHARE_HISTORY             # Share history between all sessions

# Set highlighters
ZSH_HIGHLIGHT_HIGHLIGHTERS=(brackets cursor line main pattern root)
ZSH_HIGHLIGHT_STYLES[default]=fg=none
ZSH_HIGHLIGHT_STYLES[unknown-token]=fg=red,bold
ZSH_HIGHLIGHT_STYLES[reserved-word]=fg=green
ZSH_HIGHLIGHT_STYLES[alias]=bg=blue
ZSH_HIGHLIGHT_STYLES[builtin]=bg=blue
ZSH_HIGHLIGHT_STYLES[function]=bg=blue
ZSH_HIGHLIGHT_STYLES[command]=bg=blue
ZSH_HIGHLIGHT_STYLES[precommand]=bg=blue
# ZSH_HIGHLIGHT_STYLES[commandseparator]=none
# ZSH_HIGHLIGHT_STYLES[hashed-command]=none
# ZSH_HIGHLIGHT_STYLES[path]=none
# ZSH_HIGHLIGHT_STYLES[globbing]=none
# ZSH_HIGHLIGHT_STYLES[history-expansion]=fg=blue
# ZSH_HIGHLIGHT_STYLES[single-hyphen-option]=none
# ZSH_HIGHLIGHT_STYLES[double-hyphen-option]=none
# ZSH_HIGHLIGHT_STYLES[back-quoted-argument]=none
# ZSH_HIGHLIGHT_STYLES[single-quoted-argument]=fg=yellow
# ZSH_HIGHLIGHT_STYLES[double-quoted-argument]=fg=yellow
# ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]=fg=cyan
# ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]=fg=cyan
# ZSH_HIGHLIGHT_STYLES[assign]=none

# }}}
# -----------------------------------------------------------------------------

# Functions: {{{

# Load the all function script under the ${HOME}/.zsh/functions
autoload -Uz $(print ${HOME}/.zsh/functions/*(:t)) # (:t) is strip to filename only

# }}}
# -----------------------------------------------------------------------------
[[ $ZSH_DEBUG ]] && zprof && echo 'Finished $HOME/.zshrc'


# tabtab source for yarn package
# uninstall by removing these lines or running `tabtab uninstall yarn`
[[ -f /usr/local/var/nodebrew/node/v7.1.0/lib/node_modules/yarn-completions/node_modules/tabtab/.completions/yarn.zsh ]] && . /usr/local/var/nodebrew/node/v7.1.0/lib/node_modules/yarn-completions/node_modules/tabtab/.completions/yarn.zsh
